artikel/urls.py
from django.urls import path

from artikel import views

app_name = 'artikel'

urlpatterns = [
    path('', views.daftar_artikel, name='daftar_artikel'),
    path('<int:id_artikel>/', views.detail_artikel, name='detail_artikel'),
    path('dasbor/', views.getAllArtikel, name='dasbor_artikel'),
    path('buat/', views.showCreateArtikelForm, name='buat_artikel'),
    path('ubah/<int:id_artikel>/', views.showFormWithDetailArtikel, name='ubah_artikel'),
    path('hapus/<int:id_artikel>/', views.hapus_artikel, name='hapus_artikel'),
]

debatehall/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('artikel/', include('artikel.urls')),
    path('mengumumkanhasil/', include('mengumumkanhasil.urls')),
    path('reservasi-tutor/', include('reservasi.urls')),
    path('mengeloladebat/', include('mengeloladebat.urls')),
    path('tutor/', include('personatutor.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('dummy/', views.dummy_login, name='dummy_login'),

]

artikel/models.py
from django.db import models
from tinymce import HTMLField
from datetime import datetime  
from main.models import Host

# class Artikel(models.Model):
#     id_artikel = models.AutoField(primary_key=True)
#     judul = models.CharField(max_length=100)
#     waktu_dibuat = models.DateField(default=datetime.now)
#     deskripsi = HTMLField('Content')
#     host_pembuat = models.ForeignKey(Host, blank=True, null=True, on_delete=models.SET_NULL)

#     def __str__(self):
#         return self.name

artikel/views.py
from django.http import response
from django.shortcuts import redirect, render
# from .models import Artikel
from main.models import Host, Artikel

# Controller

def daftar_artikel(request):
    response = {}
    user = request.user
    response['isHost'] = False
    if (user.is_authenticated):
      host = Host.objects.filter(user=user)
      if (len(host) > 0):
        response['isHost'] = True

    response['artikels'] = Artikel.objects.all()
    return render(request, 'daftar_artikel.html', response)

def detail_artikel(request, id_artikel):
    response = {}
    response['artikel'] = Artikel.objects.filter(id_artikel=id_artikel)[0]
    return render(request, 'detail_artikel.html', response)

def getAllArtikel(request):
    response = {}
    user = request.user
    host = Host.objects.filter(user=user)
    if (len(host) < 1):
      return redirect('artikel:daftar_artikel')
    
    host = host[0]
    response['artikels'] = Artikel.objects.all()
    return render(request, 'dasbor_artikel.html', response)

def showCreateArtikelForm(request):
    response = {}
    user = request.user
    host = Host.objects.filter(user=user)
    if (len(host) < 1):
      return redirect('artikel:daftar_artikel')
    
    host = host[0]
    if request.method == 'POST':
      judul = request.POST.get('judul')
      deskripsi = request.POST.get('deskripsi')
      artikel = Artikel(judul=judul, deskripsi=deskripsi, host_pembuat=host)
      if isValid(artikel):
        host.buatArtikel(artikel)
        return redirect('artikel:dasbor_artikel')
      else:
        response['err_msg'] = True
        response['judul'] = judul
        response['deskripsi'] = deskripsi
        return render(request, 'buat_artikel.html', response)

    else:
      return render(request, 'buat_artikel.html', response)

def showFormWithDetailArtikel(request, id_artikel):
    response = {}
    user = request.user
    host = Host.objects.filter(user=user)
    if (len(host) < 1):
      return redirect('artikel:daftar_artikel')
    
    host = host[0]
    response['id_artikel'] = id_artikel
    if request.method == 'POST':
      judul = request.POST.get('judul')
      deskripsi = request.POST.get('deskripsi')
      artikel = Artikel(judul=judul, deskripsi=deskripsi)
      if isValid(artikel):
        host.ubahArtikel(id_artikel, artikel)
        return redirect('artikel:dasbor_artikel')
      else:
        response['err_msg'] = True
        response['judul'] = judul
        response['deskripsi'] = deskripsi
        return render(request, 'ubah_artikel.html', response)        

    else:
      artikel = Artikel.objects.get(id_artikel=id_artikel)
      response['judul'] = artikel.judul
      response['deskripsi'] = artikel.deskripsi
      return render(request, 'ubah_artikel.html', response)


def hapus_artikel(request, id_artikel):
    user = request.user
    host = Host.objects.filter(user=user)
    if (len(host) < 1):
      return redirect('artikel:daftar_artikel')
    
    host = host[0]
    host.hapusArtikel(id_artikel)
    return redirect('artikel:dasbor_artikel')

# Other Function

def isValid(artikel):
    judul = artikel.judul
    deskripsi = artikel.deskripsi
    if judul == "" or judul == None or deskripsi == "" or deskripsi == None:
      return False
    return True

artikel/templates/buat_artikel.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Artikel - Ubah</title>
<script src="https://cdn.tiny.cloud/1/rits967rpft2n8zl9lpacidpbxmnslueyite3ci7574qo8tt/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
<div class="container">
    {% if err_msg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Data gagal tersimpan. Harap masukkan data yang valid!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    <h2 class="text-center my-5">Form Pembuatan Artikel</h2>
    <div class="mt-3">
      <form action="{% url 'artikel:buat_artikel' %}" method="POST">
        {% csrf_token %}
        <div class="card customcard p-4 mb-5">
          <div class="card-body">
            <div class="mb-3">
              <label for="judul" class="form-label">Judul</label>
              <input type="text" class="form-control" name="judul" value="{{ judul }}">
            </div>
            <div class="mb-3">
              <label for="deskripsi" class="form-label">Isi</label>
              <textarea type="text" class="deskripsi" name="deskripsi">{{ deskripsi }}</textarea>
            </div>
          </div>
        </div>
        <div class="text-right">
          <a href="{% url 'artikel:dasbor_artikel' %}"  type="button" class="btn customredbutton">Batal</a>
          <button type="submit" class="btn custombluebutton">Simpan</button>
        </div>
      </form>
    </div>
  </div>
  <script>
  tinymce.init({
    selector: "textarea.deskripsi",
    plugins:
      "casechange advcode advlist lists spellchecker formatpainter autoresize visualblocks tinydrive image link media imagetools wordcount",
    min_height: 380,
    menubar: false,
    toolbar: [
      "bold italic underline | forecolor | formatselect | alignleft aligncenter alignright | bullist numlist",
      "cut copy paste formatpainter removeformat | casechange visualblocks | spellchecker | link image media | code"
    ]
  });
  </script>
{% endblock content %}

artikel/templates/daftar_artikel.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Artikel</title>
  <link rel="stylesheet" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}
  <div class="container">
    <div class="mb-5">
      <h1 style="font-size: 72px;"><b>Artikel</b></h1>
      <h4>Untuk menambah wawasanmu.</h4>
      {% if isHost == True %}
      <a href="{% url 'artikel:dasbor_artikel' %}" class="btn custombluebutton">Menuju Dasbor</a>
      {% endif %}
    </div>
    <div class="mt-3 row">
      {% if artikels %}
        {% for artikel in artikels %}
          <div class="customcard m-3" style="width: 20rem;">
            <div class="card-body">
              <h4 class="card-title">{{ artikel.judul }}</h4>
              <p class="card-text text-muted h6">Hana Bahagiana | {{ artikel.waktu_dibuat }}</p>
              <a href="{% url 'artikel:detail_artikel' id_artikel=artikel.id_artikel %}" class="btn custombluebutton">Baca Selengkapnya</a>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

artikel/templates/dasbor_artikel.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Artikel</title>
  <link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="hapusModal" tabindex="-1" aria-labelledby="hapusModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="hapusModalLabel">Hapus Artikel</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-text">
        </div>
        <div class="modal-footer">
          <a id="modal-url" href="#" type="button" class="btn customredbutton">Hapus Artikel</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Body -->
  <div class="container">
    <div class="my-3">
      <h2 class="text-center mb-5">Dasbor Artikel</h2>
      <a href="{% url 'artikel:buat_artikel' %}" type="button" class="btn custombluebutton">Tambah Artikel</a>
    </div>
    <div class="mt-3">
      <table class="table table-striped table-hover table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Judul</th>
            <th>Tanggal</th>
            <th>Pembuat</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          {% if artikels %}
            {% for artikel in artikels %}
              <tr>
                <td>{{ artikel.id_artikel }}</td>
                <td>{{ artikel.judul }}</td>
                <td>{{ artikel.waktu_dibuat }}</td>
                <td>Host Name</td>
                <td>
                  <a href="{% url 'artikel:ubah_artikel' id_artikel=artikel.id_artikel %}" type="button" class="btn btn-sm custombluebutton m-1">Ubah</a>
                  <button type="button" class="btn btn-sm customredbutton m-1" data-toggle="modal"
                    data-target="#hapusModal" onclick="deleteFunc( '{{artikel.id_artikel}}' , '{{artikel.judul}}' )">Hapus</button>
                </td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
  <script>
    function deleteFunc(id, judul) {
        document.getElementById("modal-text").innerHTML = `Apakah anda yakin ingin menghapus artikel id <b>${id}</b> yang berjudul <b>${judul}</b> ?`
        document.getElementById("modal-url").href = `/artikel/hapus/${id}`
    }
  </script>
{% endblock content %}

artikel/templates/detail_artikel.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Artikel</title>
  <link rel="stylesheet" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}
  <div class="container">
    <div class="my-3">
      <h1 class="text-center mb-3">{{ artikel.judul }}</h1>
      <h6 class="text-muted">Hana Bahagiana | {{ artikel.waktu_dibuat }}</h6>
      <hr class="my-3"/>
      <p class="text-justify">
        {% autoescape on %}
          {{ artikel.deskripsi | safe }}
        {% endautoescape %}
      </p>
      <a href="{% url 'artikel:daftar_artikel' %}" class="btn custombluebutton mt-4">Lihat Artikel Lainnya</a>
    </div>
  </div>
{% endblock content %}

artikel/templates/ubah_artikel.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Artikel - Ubah</title>
<script src="https://cdn.tiny.cloud/1/rits967rpft2n8zl9lpacidpbxmnslueyite3ci7574qo8tt/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
  <div class="container">
    {% if err_msg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Data gagal tersimpan. Harap masukkan data yang valid!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    <h2 class="text-center my-5">Form Pengubahan Artikel</h2>
    <div class="mt-3">
      <form action="{% url 'artikel:ubah_artikel' id_artikel=id_artikel %}" method="POST">
        {% csrf_token %}
        <div class="card customcard p-4 mb-5">
          <div class="card-body">
            <div class="mb-3">
              <label for="judul" class="form-label">Judul</label>
              <input type="text" class="form-control" name="judul" value="{{ judul }}">
            </div>
            <div class="mb-3">
              <label for="deskripsi" class="form-label">Isi</label>
              <textarea type="text" class="deskripsi" name="deskripsi">{{ deskripsi }}</textarea>
            </div>
          </div>
        </div>
        <div class="text-right">
          <a href="{% url 'artikel:dasbor_artikel' %}"  type="button" class="btn customredbutton">Batal</a>
          <button type="submit" class="btn custombluebutton">Simpan</button>
        </div>
      </form>
    </div>
  </div>
  <script>
  tinymce.init({
    selector: "textarea.deskripsi",
    plugins:
      "casechange advcode advlist lists spellchecker formatpainter autoresize visualblocks tinydrive image link media imagetools wordcount",
    min_height: 380,
    menubar: false,
    toolbar: [
      "bold italic underline | forecolor | formatselect | alignleft aligncenter alignright | bullist numlist",
      "cut copy paste formatpainter removeformat | casechange visualblocks | spellchecker | link image media | code"
    ]
  });
  </script>
{% endblock content %}