debatehall/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('artikel/', include('artikel.urls')),
    path('mengumumkanhasil/', include('mengumumkanhasil.urls')),
    path('reservasi-tutor/', include('reservasi.urls')),
    path('mengeloladebat/', include('mengeloladebat.urls')),
    path('tutor/', include('personatutor.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('dummy/', views.dummy_login, name='dummy_login'),

]

personatutor/urls.py
from django.urls import path

from personatutor.views import show_create_persona_form, show_delete_persona, show_edit_persona_form, show_persona_tutor, show_persona_tutor_list 

app_name = 'personatutor'

urlpatterns = [
    path('', show_persona_tutor_list, name='daftar'),
    path('createpersonatutor', show_create_persona_form, name='create'),
    path('<int:id>', show_persona_tutor, name='show'),
    path('<int:id>/edit', show_edit_persona_form, name='edit'),
    path('<int:id>/delete', show_delete_persona, name='delete'),
]

reservasi/urls.py
from django.urls import path

from . import views

app_name = 'reservasi'

urlpatterns = [
    path('', views.list_reservasi, name='list-reservasi'),
    path('<int:id>/create', views.create_reservasi, name='create'),
    path('<int:id>/bayar', views.bayar_reservasi, name='bayar'),
    path('<int:id>/cancel', views.cancel_reservasi, name='cancel'),
]

personatutor/models.py
from typing import DefaultDict
from django.db import models

# Create your models here.

class PersonaTutor(models.Model):
    waktu = (
        ('H', '1 Hari'),
        ('M', '1 Minggu'),
        ('B', '1 Bulan'),
    )
    nama = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    tentang_tutor = models.TextField(max_length=1000, blank=True)
    deskripsi_kursus = models.TextField(max_length=1000, blank=True)
    jadwal = models.CharField(max_length=1, choices=waktu, blank=True)
    harga = models.PositiveIntegerField(blank=True, null=True)
    ready = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.ready = True

        if not self.nama:
            self.ready = False
        if not self.email:
            self.ready = False
        if not self.tentang_tutor:
            self.ready = False
        if not self.deskripsi_kursus:
            self.ready = False
        if not self.jadwal:
            self.ready = False
        if not self.harga:
            self.ready = False

        super(PersonaTutor, self).save(*args, **kwargs)
    
    def __str__(self):
        if self.nama:
            return self.nama
        else:
            return "Unknown"

personatutor/forms.py
from django import forms
from .models import PersonaTutor

class Form(forms.ModelForm):
    class Meta:
        model = PersonaTutor
        fields = ['nama', 'email', 'tentang_tutor', 'deskripsi_kursus', 'jadwal', 'harga']
 

personatutor/views.py
from django.shortcuts import (get_object_or_404, render, redirect, HttpResponseRedirect)
from django.urls import reverse
from main.models import Pendebat, Tutor
from .forms import Form
from .models import PersonaTutor

# Create your views here.
def show_persona_tutor(request, id):
    persona = PersonaTutor.objects.get(id=id)
    tutor = Tutor.objects.get(persona=persona)
    show_option = False
    show_reservasi = False
    try:
        if Tutor.objects.get(id=request.user.id).persona == persona:
            show_option = True
        if Pendebat.objects.get(id=request.user.id):
            show_reservasi = True
    except:
        pass

    response = {
        'data' : persona,
        'tutor' : tutor,
        'show_option': show_option,
        'show_reservasi': show_reservasi
    }
    return render(request, 'personatutor/personatutor.html', response)

def show_persona_tutor_list(request):
    show_id = 0
    create = False
    try:
        tutor = Tutor.objects.get(id=request.user.id)
        print(tutor)
        print(tutor.persona)
        if tutor:
            if not tutor.persona:
                create = True
            else:
                show_id = tutor.persona.id
    except:
        pass

    response = {
        'dataset' : PersonaTutor.objects.filter(ready=True),
        'create' : create,
        'show_id' : show_id,
    }
    return render(request, 'personatutor/personatutorlist.html', response)

def show_create_persona_form(request):
    form = Form(request.POST or None)
    tutor = request.user
    is_tutor = False

    try:
        tutor = Tutor.objects.get(id=request.user.id)
        is_tutor = True
    except:
        pass

    if form.is_valid() and request.method =='POST':
        tutor.buatPersona(form)
        return HttpResponseRedirect(reverse('personatutor:daftar'))

    response = {
        'form' : form,
        'tutor': tutor,
        'is_tutor' : is_tutor
    }

    return render(request, 'personatutor/personatutorcreate.html', response)

def show_edit_persona_form(request, id):
    obj = get_object_or_404(PersonaTutor, id=id)
    form = Form(request.POST or None, instance=obj)
    tutor = request.user
    try:
        tutor = Tutor.objects.get(id=request.user.id)
    except:
        pass

    if form.is_valid() and request.method =='POST':
        tutor.ubahPersona(form)
        return HttpResponseRedirect(reverse('personatutor:show', args=[id]))

    response = {
        'form' : form,
        'id' : id,
        'tutor' : tutor,
    }
    return render(request, 'personatutor/personatutoredit.html', response)

def show_delete_persona(request, id):
    try:
        tutor = Tutor.objects.get(id=request.user.id)

        if tutor and int(tutor.persona.id) == int(id):
            tutor.hapusPersona(id)
            return redirect('personatutor:daftar')
    except:
        return render(request, 'personatutor/personatutorerror.html')

personatutor/templates/personatutor/personatutor.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Persona Tutor - {{ data.nama }}</title>
    <link rel="stylesheet" href="{% static 'css/persona.css' %}">
{% endblock meta %}

{% block content %}

<div id="persona-tutor">
    <div class="container" >
        <div class="row">
            <div class="col">
                <div class="persona-header">
                    <div class="persona-name">
                        <p style="font-weight: bolder; font-size: 36px; padding-right: 10px;">{{ data.nama|default:"Unknown name"}}</p>
                        {% if show_option %}
                        <a href="{% url 'personatutor:edit' id=data.id %}" class="icon-edit"><i class="fas fa-edit"></i></a>
                        <a data-toggle="modal" data-target="#exampleModalCenter" class="icon-delete"><i class="fas fa-trash"></i></a>
                        {% endif %}
                    </div>
                    <p>{{ data.email|default:"Unknown email"}}</p>
                </div>
                <div class="persona-desc">
                    <p style="font-size: 18px; font-weight: bold;">Tentang Tutor</p>
                    <p> {{ data.tentang_tutor|default:"Unknown description" }}</p>
                </div>
                <div class="persona-desc">
                    <p style="font-size: 18px; font-weight: bold;">Deskripsi Kursus</p>
                    <p> {{ data.deskripsi_kursus|default:"Unknown description" }}</p>
                </div>
                <div class="persona-desc">
                    <p style="font-size: 18px; font-weight: bold;">Jadwal Kursus</p>
                    <p> {{ data.get_jadwal_display|default:"Unknown Schedule" }}</p>
                </div>
            </div>
            <div class="col-md-auto persona-right">
                <img class="profile-pict" src='https://i.ibb.co/1L3cVVn/barb.jpg' alt='' style="width: 250px;">
                <div style="margin-top: 40px;">
                    {% if data.harga %}
                        <p style="font-size: 24px; font-weight: bold;">Rp{{ data.harga }}</p>
                    {% else %}
                        <p style="font-size: 24px; font-weight: bold;">Unknown price</p>
                    {% endif %}
                    {% if data.ready and request.session.role == 'pendebat' %}
                    <button class="btn"><a data-toggle="modal" data-target="#modalReservasi" style="text-decoration: none; color: #FFFFFF;font-size: 18px;">Reservasi Tutor</a></button>
                    {% endif %}
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Hapus Persona</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <p>Apakah anda yakin untuk menghapus persona tutor? Tekan 'OK' untuk melanjutkan hapus persona tutor.</p>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary batal" data-dismiss="modal">Cancel</button>
                    <a class="btn" href="{% url 'personatutor:delete' id=data.id %}">OK</a>
                    </div>
                </div>
                </div>
            </div>
            <!-- Modal Konfirmasi Reservasi -->
            <div class="modal fade" id="modalReservasi" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Konfirmasi Reservasi</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                    <p style="color:#1D3557; font-size: 18px;font-weight: 900;">Apakah anda yakin untuk membuat reservasi? Tekan 'OK' untuk lanjut reservasi.</p>
                    </div>
                    <div class="modal-footer">
                    <button id="kembali" data-dismiss="modal">Cancel</button>
                    <a class="btn" href="{% url 'reservasi:create' id=tutor.id %}">OK</a>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

personatutor/templates/personatutor/personatutorcreate.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Buat Persona Tutor</title>
    <link rel="stylesheet" href="{% static 'css/persona.css' %}">
{% endblock meta %}

{% block content %}

<div id="persona-tutor-create">
    <div class="container" >
        {% if is_tutor %}
        {% if not tutor.persona %}
        <div>
            <p style="font-size: 36px; font-weight: bolder; margin-bottom: 10px;">Daftar Persona Tutor</p>
            <p>Layanan tutor untuk mendapatkan pengajaran dari tutor terbaik yang ada</p>
        </div>
        
        <form method="POST">
        {% csrf_token %}
            {{ form }}
            <div class="d-flex justify-content-end">
                <button class="btn batal">Batal</button>
                <input class="btn simpan" type="submit" value="Simpan">
            </div>
        </form>
        
        {% else %}
        <div>
            <h3>Can Only Create One Persona.</h3>
        </div>
        {% endif %}
        {% else %}
        <div>
            <h3>Only Tutor Can Create Persona Tutor.</h3>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

personatutor/templates/personatutor/personatutoredit.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Edit Persona Tutor</title>
    <link rel="stylesheet" href="{% static 'css/persona.css' %}">
{% endblock meta %}

{% block content %}

<div id="persona-tutor-edit">
    <div class="container" >
        {% if tutor.persona.id == id|add:"0" %}
        <div>
            <p style="font-size: 36px; font-weight: bolder; margin-bottom: 10px;">Edit Persona Tutor</p>
            <p>Edit informasi persona tutor Anda</p>
        </div>
        
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <div class="d-flex justify-content-end">
                <a class="btn batal" href="{% url 'personatutor:show' id=id %}">Batal</a>
                <input class="btn simpan" type="submit" value="Simpan">
            </div>
        </form>

        {% else %}
        <div>
            <h3>You Need to Have Persona Tutor First.</h3>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

personatutor/templates/personatutor/personatutorerror.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Error</title>
    <link rel="stylesheet" href="{% static 'css/persona.css' %}">
{% endblock meta %}

{% block content %}

<div id="persona-tutor-eror">
    <div class="container" >
        <h3>Permission Denied to Access This Page.</h3>
    </div>
</div>

{% endblock content %}

personatutor/templates/personatutor/personatutorlist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Persona Tutor</title>
    <link rel="stylesheet" href="{% static 'css/persona.css' %}">
{% endblock meta %}

{% block content %}

<div id="persona-tutor-list">
    <div class="container" >
        <div>
            <p style="font-size: 36px; font-weight: bolder; margin-bottom: 10px;">Daftar Tutor</p>
            <p>Layanan tutor untuk mendapatkan pengajaran dari tutor terbaik yang ada</p>
        </div>
        
        {% if create %}
            <a class="btn" href="{% url 'personatutor:create' %}">Buat Persona Tutor</a>
        {% elif show_id %}
            <a class="btn" href="{% url 'personatutor:show' id=show_id %}">Lihat Persona Tutor Saya</a>
        {% endif %}

        {% if dataset %}
        <div class="persona-list">
            {% for data in dataset%}
            <div class="row">
                <div class="col-md-auto" style="width: 150px;">
                    <img class="profile-pict" src='https://i.ibb.co/1L3cVVn/barb.jpg' alt='' style="width: 100px;">
                </div>
                <div class="col">
                    <p style="font-size: 24px; font-weight: bold; margin-bottom: 10px;">{{ data.nama }}</p>
                    <p>{{ data.harga }}</p>
                </div>
                <div class="col-md-auto">
                    <a class="btn" href="{% url 'personatutor:show' id=data.id %}">Lihat Tutor</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}