artikel/urls.py
from django.urls import path

from artikel import views

app_name = 'artikel'

urlpatterns = [
    path('', views.daftar_artikel, name='daftar_artikel'),
    path('<int:id_artikel>/', views.detail_artikel, name='detail_artikel'),
    path('dasbor/', views.getAllArtikel, name='dasbor_artikel'),
    path('buat/', views.showCreateArtikelForm, name='buat_artikel'),
    path('ubah/<int:id_artikel>/', views.showFormWithDetailArtikel, name='ubah_artikel'),
    path('hapus/<int:id_artikel>/', views.hapus_artikel, name='hapus_artikel'),
]

debatehall/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('artikel/', include('artikel.urls')),
    path('mengumumkanhasil/', include('mengumumkanhasil.urls')),
    path('reservasi-tutor/', include('reservasi.urls')),
    path('mengeloladebat/', include('mengeloladebat.urls')),
    path('tutor/', include('personatutor.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('dummy/', views.dummy_login, name='dummy_login'),

]

personatutor/urls.py
from django.urls import path

from personatutor.views import show_create_persona_form, show_delete_persona, show_edit_persona_form, show_persona_tutor, show_persona_tutor_list 

app_name = 'personatutor'

urlpatterns = [
    path('', show_persona_tutor_list, name='daftar'),
    path('createpersonatutor', show_create_persona_form, name='create'),
    path('<int:id>', show_persona_tutor, name='show'),
    path('<int:id>/edit', show_edit_persona_form, name='edit'),
    path('<int:id>/delete', show_delete_persona, name='delete'),
]

reservasi/urls.py
from django.urls import path

from . import views

app_name = 'reservasi'

urlpatterns = [
    path('', views.list_reservasi, name='list-reservasi'),
    path('<int:id>/create', views.create_reservasi, name='create'),
    path('<int:id>/bayar', views.bayar_reservasi, name='bayar'),
    path('<int:id>/cancel', views.cancel_reservasi, name='cancel'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="icon" href="https://nursing.sgtuniversity.ac.in/wp-content/uploads/2017/05/debate.png" type="image/icon type">
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/c883358289.js" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include 'navbar.html' %}

  {% comment %} content {% endcomment %}
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>
  
  {% include 'footer.html' %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>

</html>

templates/base_loggedin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/c883358289.js" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include 'navbar_loggedin.html' %}

  {% comment %} content {% endcomment %}
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>
  
  {% include 'footer.html' %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html
<div id="footer" class="fixed-bottom">
    <div class="container" >
        <p style="font-size: 24px;font-weight: bold;">DebateHall</p>
        <p>by DebateHall</p>
        <p style="margin: 30px 0;">Amanda Carissa<br>Ferdi Fadillah<br>Muhammad Fayaad<br>Naufal Pramudya<br>Natasya Zahra</p>
        <p>RPL Kelas B Ganjil 2021/2022</p>
    </div>
</div>

templates/navbar.html
<div id="navbar">
    <div class="topnav" >
        <a href="{% url 'main:home' %}" style="font-weight: bold;">Debate<span style="color:#E63946;">Hall</span></a>
        {% if user.is_authenticated %}
          <a href="{% url 'main:logout' %}">Keluar</a>
        {% else %}
          <a href="{% url 'main:login' %}">Masuk</a>
        {% endif %}
        {% if request.session.role == 'pendebat' %}
          <a href="{% url 'reservasi:list-reservasi' %}">Reservasi Saya</a>
        {% endif %}
        <a href="{% url 'artikel:daftar_artikel' %}">Artikel</a>
        <a href="{% url 'personatutor:daftar' %}">Tutor</a>
        <a href="/mengeloladebat/listdebat">Debat</a>
        <a href="/mengumumkanhasil/">Hasil Debat</a>
    </div>
</div>

templates/navbar_loggedin.html
<div id="navbar">
    <div class="topnav" >
        <a href="{% url 'main:home' %}" style="font-weight: bold;">Debate<span style="color:#E63946;">Hall</span></a>
        <a href="">Profil</a>
        <a href="{% url 'reservasi:list-reservasi' %}">Reservasi Saya</a>
        <a href="">Artikel</a>
        <a href="">Tutor</a>
        <a href="/mengeloladebat/listdebat">Debat</a>
        <a href="/mengumumkanhasil/">Hasil Debat</a>
    </div>
</div>