debatehall/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('artikel/', include('artikel.urls')),
    path('mengumumkanhasil/', include('mengumumkanhasil.urls')),
    path('reservasi-tutor/', include('reservasi.urls')),
    path('mengeloladebat/', include('mengeloladebat.urls')),
    path('tutor/', include('personatutor.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('dummy/', views.dummy_login, name='dummy_login'),

]

mengumumkanhasil/urls.py
from django.urls import path

from . import views

app_name = 'mengumumkanhasil'

urlpatterns = [
    #path('/formulir_hasil', views.formulir_hasil, name='formulir_hasil'),
    path('', views.daftar_hasil, name='daftar_hasil'),
    path('hasil_debat', views.hasil_debat, name='hasil_debat'),
    path('dasbor/', views.getAllHasil, name='dasbor_hasil'),
    path('<int:id_hasil>/', views.detail_hasil, name='detail_hasil'),
    path('ubah/<int:id_hasil>/', views.showFormWithDetailArtikel, name='ubah_hasil'),
    path('formulir_hasil', views.showCreateArtikelForm, name='formulir_hasil'),
    path('hapus/<int:id_hasil>/', views.hapus_hasil, name='hapus_hasil'),
]

mengumumkanhasil/models.py
from django.db import models
from mengeloladebat.models import Debat
from main.models import Juri
from tinymce import HTMLField
from datetime import datetime

# Create your models here.

# class HasilDebat(models.Model):
#     id_hasil = models.AutoField(primary_key=True)
#     debatModel = models.ForeignKey(Debat, blank=True, null=True, on_delete=models.SET_NULL)
#     pm = models.CharField(max_length=50)
#     dpm = models.CharField(max_length=50)
#     gw = models.CharField(max_length=50)
#     pm_score = models.IntegerField(null=True, blank=True)
#     dpm_score = models.IntegerField(null=True, blank=True)
#     gw_score = models.IntegerField(null=True, blank=True)
#     oo = models.CharField(max_length=50)
#     dlo = models.CharField(max_length=50)
#     ow = models.CharField(max_length=50)
#     oo_score = models.IntegerField(null=True, blank=True)
#     dlo_score = models.IntegerField(null=True, blank=True)
#     ow_score = models.IntegerField(null=True, blank=True)
#     general_comment = HTMLField('Content')
#     juri_pembuat = models.ForeignKey(Juri, blank=True, null=True, on_delete=models.SET_NULL)
 
#     def __str__(self):
#         return "hasil debat " + self.debatModel.judul

mengumumkanhasil/views.py
from django.shortcuts import render, redirect
from mengeloladebat.models import Debat
from main.models import Juri, HasilDebat

# def formulir_hasil(request):
#     return render(request, 'mengumumkanhasil/formulir_hasil.html')

def hasil_debat(request):
    return render(request, 'mengumumkanhasil/formulir_hasil.html')
  
def daftar_hasil(request):
    response = {}
    user = request.user
    response['isJuri'] = False
    if (user.is_authenticated):
      juri = Juri.objects.filter(user=user)
      if (len(juri) > 0):
        response['isJuri'] = True

    response['hasils'] = HasilDebat.objects.all()
    return render(request, 'mengumumkanhasil/daftar_hasil.html', response)
  
def getAllHasil(request):
    response = {}
    user = request.user
    juri = Juri.objects.filter(user=user)
    if (len(juri) < 1):
      return redirect('mengumumkanhasil:daftar_hasil')
    
    juri = juri[0]
    response['hasils'] = HasilDebat.objects.all()
    return render(request, 'mengumumkanhasil/dasbor_hasil.html', response)
  
def detail_hasil(request, id_hasil):
    response = {}
    response['hasil'] = HasilDebat.objects.filter(id_hasil=id_hasil)[0]
    return render(request, 'mengumumkanhasil/hasil_debat.html', response)

def showCreateArtikelForm(request):
    response = {}
    
    user = request.user
    juri = Juri.objects.filter(user=user)
    if (len(juri) < 1):
      return redirect('mengumumkanhasil:daftar_hasil')
    
    juri = juri[0]
    if request.method == 'POST':
      id_hasil = pm = request.POST.get('iddebat')
      iddebat = request.POST.get('iddebat')
      debat = Debat.objects.get(iddebat=request.POST.get('iddebat'))
      pm = request.POST.get('pm')
      dpm = request.POST.get('dpm')
      gw = request.POST.get('gw')
      pm_score  = request.POST.get('pm_score')
      dpm_score = request.POST.get('dpm_score')
      gw_score = request.POST.get('gw_score')
      oo = request.POST.get('oo')
      dlo = request.POST.get('dlo')
      ow = request.POST.get('ow')
      oo_score = request.POST.get('oo_score')
      dlo_score = request.POST.get('dlo_score')
      ow_score = request.POST.get('ow_score')
      general_comment = request.POST.get('general_comment')
      
      hasildebat = HasilDebat( id_hasil = id_hasil, debatModel= debat, \
                              pm=pm, dpm=dpm, gw=gw, \
                              pm_score=pm_score, dpm_score=dpm_score, gw_score=gw_score, \
                              oo=oo, dlo=dlo, ow=ow, \
                              oo_score=oo_score, dlo_score=dlo_score, ow_score=ow_score, \
                                  general_comment=general_comment, juri_pembuat=juri)
      if isValid(hasildebat):
        juri.buatHasilDebat(hasildebat)
        return redirect('mengumumkanhasil:dasbor_hasil')
      else:
        response['err_msg'] = True
        response['id_hasil'] = id_hasil
        response['iddebat'] = iddebat
        response['pm'] = pm
        response['dpm'] = dpm
        response['gw'] = gw
        response['pm_score'] = pm_score
        response['dpm_score'] = dpm_score
        response['gw_score'] = gw_score
        response['oo'] = oo
        response['dlo'] = dlo
        response['ow'] = ow
        response['oo_score'] = oo_score
        response['dlo_score'] = dlo_score
        response['ow_score'] = ow_score
        response['general_comment'] = general_comment        
        return render(request, 'mengumumkanhasil/formulir_hasil.html', response)

    else:
        return render(request, 'mengumumkanhasil/formulir_hasil.html', response)

def showFormWithDetailArtikel(request, id_hasil):
    response = {}
    user = request.user
    juri = Juri.objects.filter(user=user)
    if (len(juri) < 1):
      return redirect('mengumumkanhasil:daftar_hasil')
    
    juri = juri[0]
    response['id_hasil'] = id_hasil
    if request.method == 'POST':
      pm = request.POST.get('pm')
      dpm = request.POST.get('dpm')
      gw = request.POST.get('gw')
      pm_score  = request.POST.get('pm_score')
      dpm_score = request.POST.get('dpm_score')
      gw_score = request.POST.get('gw_score')
      oo = request.POST.get('oo')
      dlo = request.POST.get('dlo')
      ow = request.POST.get('ow')
      oo_score = request.POST.get('oo_score')
      dlo_score = request.POST.get('dlo_score')
      ow_score = request.POST.get('ow_score')
      general_comment = request.POST.get('general_comment')
      hasildebat = HasilDebat(pm=pm, dpm=dpm, gw=gw, \
                              pm_score=pm_score, dpm_score=dpm_score, gw_score=gw_score, \
                              oo=oo, dlo=dlo, ow=ow, \
                              oo_score=oo_score, dlo_score=dlo_score, ow_score=ow_score, \
                                  general_comment=general_comment)
      if isValid(hasildebat):
        juri.ubahHasilDebat(id_hasil, hasildebat)
        return redirect('mengumumkanhasil:dasbor_hasil')
      else:
        response['err_msg'] = True
        response['pm'] = pm
        response['dpm'] = dpm
        response['gw'] = gw
        response['pm_score'] = pm_score
        response['dpm_score'] = dpm_score
        response['gw_score'] = gw_score
        response['oo'] = oo
        response['dlo'] = dlo
        response['ow'] = ow
        response['oo_score'] = oo_score
        response['dlo_score'] = dlo_score
        response['ow_score'] = ow_score
        response['general_comment'] = general_comment  
        return render(request, 'mengumumkanhasil/ubah_hasil.html', response)        

    else:
      hasildebat = HasilDebat.objects.get(id_hasil=id_hasil)
      response['pm'] = hasildebat.pm
      response['dpm'] = hasildebat.dpm
      response['gw'] = hasildebat.gw
      response['pm_score'] = hasildebat.pm_score
      response['dpm_score'] = hasildebat.dpm_score
      response['gw_score'] = hasildebat.gw_score
      response['oo'] = hasildebat.oo
      response['dlo'] = hasildebat.dlo
      response['ow'] = hasildebat.ow
      response['oo_score'] = hasildebat.oo_score
      response['dlo_score'] = hasildebat.dlo_score
      response['ow_score'] = hasildebat.ow_score
      response['general_comment'] = hasildebat.general_comment  
      return render(request, 'mengumumkanhasil/ubah_hasil.html', response)


def hapus_hasil(request, id_hasil):
    user = request.user
    juri = Juri.objects.filter(user=user)
    
    if (len(juri) < 1):
      return redirect('mengumumkanhasil:daftar_hasil')
    
    juri = juri[0]
    juri.hapusHasilDebat(id_hasil)
    return redirect('mengumumkanhasil:dasbor_hasil')

# Other Function

def isValid(hasil):
    pm = hasil.pm
    dpm = hasil.dpm
    gw = hasil.gw
    pm_score  = hasil.pm_score
    dpm_score = hasil.dpm_score
    gw_score = hasil.gw_score
    oo = hasil.oo
    dlo = hasil.dlo
    ow = hasil.ow
    oo_score = hasil.oo_score
    dlo_score = hasil.dlo_score
    ow_score = hasil.ow_score
    general_comment = hasil.general_comment
    if pm == "" or pm == None or \
        dpm == "" or dpm == None or \
         gw == "" or gw == None or \
            pm_score == "" or pm_score  == None or \
              dpm_score == "" or dpm_score == None or \
                gw_score == "" or gw_score == None or \
                 oo== "" or oo == None or \
                    dlo == "" or dlo == None or \
                      ow == "" or ow == None or \
                        oo_score== "" or oo_score == None or \
                          dlo_score == "" or dlo_score == None or \
                            ow_score == "" or ow_score == None or \
                              general_comment == "" or general_comment == None :
      return False
    return True

mengumumkanhasil/templates/mengumumkanhasil/daftar_hasil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Hasil Debat</title>
  <link rel="stylesheet" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}
  <div class="container">
    <div class="mb-5">
      <h1 style="font-size: 72px;"><b>Hasil Debat</b></h1>
      {% if isJuri == True %}
      <a href="{% url 'mengumumkanhasil:dasbor_hasil' %}" class="btn custombluebutton">Menuju Dasbor</a>
      {% endif %}
    </div>
    <div class="mt-3 row">
      {% if hasils %}
        {% for hasil in hasils %}
          <div class="customcard m-3" style="width: 20rem;">
            <div class="card-body">
              <h4 class="card-title">Hasil Debat {{ hasil.debatModel.judul }}</h4>
              <a href="{% url 'mengumumkanhasil:detail_hasil' id_hasil=hasil.id_hasil %}" class="btn custombluebutton">Baca Selengkapnya</a>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

mengumumkanhasil/templates/mengumumkanhasil/dasbor_hasil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Hasil Debat</title>
  <link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="hapusModal" tabindex="-1" aria-labelledby="hapusModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="hapusModalLabel">Hapus Hasil</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-text">
        </div>
        <div class="modal-footer">
          <a id="modal-url" href="#" type="button" class="btn customredbutton">Hapus Hasil</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Body -->
  <div class="container">
    <div class="my-3">
      <h2 class="text-center mb-5">Dasbor Hasil</h2>
      <a href="{% url 'mengumumkanhasil:formulir_hasil' %}" type="button" class="btn custombluebutton">Tambah Hasil</a>
    </div>
    <div class="mt-3">
      <table class="table table-striped table-hover table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Judul</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          {% if hasils %}
            {% for hasil in hasils %}
              <tr>
                <td>{{ hasil.id_hasil }}</td>
                <td>Hasil Debat {{ hasil.debatModel.judul }}</td>
                <td>
                  <a href="{% url 'mengumumkanhasil:ubah_hasil' id_hasil=hasil.id_hasil %}" type="button" class="btn btn-sm custombluebutton m-1">Ubah</a>
                  <button type="button" class="btn btn-sm customredbutton m-1" data-toggle="modal"
                    data-target="#hapusModal" onclick="deleteFunc( '{{hasil.id_hasil}}' )">Hapus</button>
                </td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
  <script>
    function deleteFunc(id) {
        document.getElementById("modal-text").innerHTML = `Apakah anda yakin ingin menghapus artikel id <b>${id}</b>?`
        document.getElementById("modal-url").href = `/mengumumkanhasil/hapus/${id}`
    }
  </script>
{% endblock content %}

mengumumkanhasil/templates/mengumumkanhasil/formulir_hasil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>HasilDebat - Buat</title>
<script src="https://cdn.tiny.cloud/1/rits967rpft2n8zl9lpacidpbxmnslueyite3ci7574qo8tt/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
<div class="container">
    {% if err_msg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Data gagal tersimpan. Harap masukkan data yang valid!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    <h2 class="text-center my-5">Form Pembuatan Hasil Debat</h2>
    <div class="mt-3">
      <form action="{% url 'mengumumkanhasil:formulir_hasil' %}" method="POST">
        {% csrf_token %}
        <div class="card customcard p-4 mb-5">
          <div class="card-body">
            <div class="mb-3">
              <label for="pk_id" class="form-label">iddebat</label>
              <input type="text" class="form-control" name="iddebat" value="{{ iddebat }}">

              <label for="pm" class="form-label">pm</label>
              <input type="text" class="form-control" name="pm" value="{{ pm }}">
              <label for="dpm" class="form-label">dpm</label>
              <input type="text" class="form-control" name="dpm" value="{{ dpm }}">
              <label for="gw" class="form-label">gw</label>
              <input type="text" class="form-control" name="gw" value="{{ gw }}">

              <label for="pm_score" class="form-label">pm_score</label>
              <input type="text" class="form-control" name="pm_score" value="{{ pm_score }}">
              <label for="dpm_score" class="form-label">dpm_score</label>
              <input type="text" class="form-control" name="dpm_score" value="{{ dpm_score }}">
              <label for="gw_score" class="form-label">gw_score</label>
              <input type="text" class="form-control" name="gw_score" value="{{ gw_score }}">

              <label for="oo" class="form-label">oo</label>
              <input type="text" class="form-control" name="oo" value="{{ oo }}">
              <label for="dlo" class="form-label">dlo</label>
              <input type="text" class="form-control" name="dlo" value="{{ dlo }}">
              <label for="ow" class="form-label">ow</label>
              <input type="text" class="form-control" name="ow" value="{{ ow }}">

              <label for="oo_score" class="form-label">oo_score</label>
              <input type="text" class="form-control" name="oo_score" value="{{ oo_score }}">
              <label for="dlo_score" class="form-label">dlo_score</label>
              <input type="text" class="form-control" name="dlo_score" value="{{ dlo_score }}">
              <label for="ow_score" class="form-label">ow_score</label>
              <input type="text" class="form-control" name="ow_score" value="{{ ow_score }}">
      
            </div>
            <div class="mb-3">
              <label for="general_comment" class="form-label">Isi</label>
              <textarea type="text" class="general_comment" name="general_comment">{{ general_comment }}</textarea>
            </div>
          </div>
        </div>
        <div class="text-right">
          <a href="{% url 'mengumumkanhasil:dasbor_hasil' %}"  type="button" class="btn customredbutton">Batal</a>
          <button type="submit" class="btn custombluebutton">Simpan</button>
        </div>
      </form>
    </div>
  </div>
  <script>
  tinymce.init({
    selector: "textarea.general_comment",
    plugins:
      "casechange advcode advlist lists spellchecker formatpainter autoresize visualblocks tinydrive image link media imagetools wordcount",
    min_height: 380,
    menubar: false,
    toolbar: [
      "bold italic underline | forecolor | formatselect | alignleft aligncenter alignright | bullist numlist",
      "cut copy paste formatpainter removeformat | casechange visualblocks | spellchecker | link image media | code"
    ]
  });
  </script>
{% endblock content %}

mengumumkanhasil/templates/mengumumkanhasil/hasil_debat.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hasil Debat</title>
<script>
  // The function below will start the confirmation dialog
  function confirmAction() {
    let confirmAction = confirm("Yakin mengumumkan hasil? Ini final jadi tidak bisa diunpublish");
    if (confirmAction) {
      alert("Action successfully executed");
      window.location.href = "/mengeloladebat/1";
    } else {
      alert("Action canceled");
    }
  }

  function deleteConfirmAction() {
    let confirmAction = confirm("Yakin hapus?");
    if (confirmAction) {
      alert("Action successfully executed");
      window.location.href = "/mengeloladebat/1";
    } else {
      alert("Action canceled");
    }
  }
</script>
{% endblock meta %}

{% block content %}
  <h1>Formulir Hasil Debat</h1>
  <h2>Hasil Debat {{ hasil.debatModel.judul }}</h2>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="formGroupExampleInput">Government</label>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.pm }} 
            <span class="badge badge-primary badge-pill">{{ hasil.pm_score }} </span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.dpm }} 
            <span class="badge badge-primary badge-pill">{{ hasil.dpm_score }} </span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.gw }} 
            <span class="badge badge-primary badge-pill">{{ hasil.gw_score }} </span>
        </li>
      </ul>
    </div>

    <div class="form-group col-md-6">
      <label for="formGroupExampleInput">Opposition</label>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.oo }} 
            <span class="badge badge-primary badge-pill">{{ hasil.oo_score }} </span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.dlo }} 
            <span class="badge badge-primary badge-pill">{{ hasil.dlo_score }} </span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ hasil.ow }} 
            <span class="badge badge-primary badge-pill">{{ hasil.ow_score }} </span>
        </li>
      </ul>
    </div>
  </div>
   
  <div class="form-group">
    <label for="exampleFormControlTextarea1">General Comment</label>
    <p>
      {{ hasil.general_comment | safe }} 
    </p>
  </div>
  
{% endblock content %}

mengumumkanhasil/templates/mengumumkanhasil/ubah_hasil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>HasilDebat - Buat</title>
<script src="https://cdn.tiny.cloud/1/rits967rpft2n8zl9lpacidpbxmnslueyite3ci7574qo8tt/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<link rel="stylesheet" href="{% static 'css/artikel.css' %}"> 
{% endblock meta %}

{% block content %}
<div class="container">
    {% if err_msg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Data gagal tersimpan. Harap masukkan data yang valid!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    <h2 class="text-center my-5">Form Pengubahan Hasil Debat</h2>
    <div class="mt-3">
      <form action="{% url 'mengumumkanhasil:ubah_hasil' id_hasil=id_hasil %}" method="POST">
        {% csrf_token %}
        <div class="card customcard p-4 mb-5">
          <div class="card-body">
            <div class="mb-3">
              {% comment %} <label for="pk_id" class="form-label">id_hasil</label>
              <input type="text" class="form-control" name="id_hasil" value="{{ id_hasil }}">

              <label for="pk_id" class="form-label">iddebat</label>
              <input type="text" class="form-control" name="iddebat" value="{{ iddebat }}"> {% endcomment %}

              <label for="pm" class="form-label">pm</label>
              <input type="text" class="form-control" name="pm" value="{{ pm }}">
              <label for="dpm" class="form-label">dpm</label>
              <input type="text" class="form-control" name="dpm" value="{{ dpm }}">
              <label for="gw" class="form-label">gw</label>
              <input type="text" class="form-control" name="gw" value="{{ gw }}">

              <label for="pm_score" class="form-label">pm_score</label>
              <input type="text" class="form-control" name="pm_score" value="{{ pm_score }}">
              <label for="dpm_score" class="form-label">dpm_score</label>
              <input type="text" class="form-control" name="dpm_score" value="{{ dpm_score }}">
              <label for="gw_score" class="form-label">gw_score</label>
              <input type="text" class="form-control" name="gw_score" value="{{ gw_score }}">

              <label for="oo" class="form-label">oo</label>
              <input type="text" class="form-control" name="oo" value="{{ oo }}">
              <label for="dlo" class="form-label">dlo</label>
              <input type="text" class="form-control" name="dlo" value="{{ dlo }}">
              <label for="ow" class="form-label">ow</label>
              <input type="text" class="form-control" name="ow" value="{{ ow }}">

              <label for="oo_score" class="form-label">oo_score</label>
              <input type="text" class="form-control" name="oo_score" value="{{ oo_score }}">
              <label for="dlo_score" class="form-label">dlo_score</label>
              <input type="text" class="form-control" name="dlo_score" value="{{ dlo_score }}">
              <label for="ow_score" class="form-label">ow_score</label>
              <input type="text" class="form-control" name="ow_score" value="{{ ow_score }}">
      
            </div>
            <div class="mb-3">
              <label for="general_comment" class="form-label">Isi</label>
              <textarea type="text" class="general_comment" name="general_comment">{{ general_comment }}</textarea>
            </div>
          </div>
        </div>
        <div class="text-right">
          <a href="{% url 'mengumumkanhasil:dasbor_hasil' %}"  type="button" class="btn customredbutton">Batal</a>
          <button type="submit" class="btn custombluebutton">Simpan</button>
        </div>
      </form>
    </div>
  </div>
  <script>
  tinymce.init({
    selector: "textarea.general_comment",
    plugins:
      "casechange advcode advlist lists spellchecker formatpainter autoresize visualblocks tinydrive image link media imagetools wordcount",
    min_height: 380,
    menubar: false,
    toolbar: [
      "bold italic underline | forecolor | formatselect | alignleft aligncenter alignright | bullist numlist",
      "cut copy paste formatpainter removeformat | casechange visualblocks | spellchecker | link image media | code"
    ]
  });
  </script>
{% endblock content %}